# Generated by Django 3.2.4 on 2021-07-15 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_Department_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settings_Sort_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_sort_name', models.CharField(default='', max_length=200)),
                ('leave_days', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'leaveappdata_settings_sort_form',
            },
        ),
        migrations.CreateModel(
            name='Leave_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('duration1', models.CharField(choices=[('เต็มวัน', 'เต็มวัน'), ('ครึ่งเช้า', 'ครึ่งเช้า'), ('ครึ่งบ่าย', 'ครึ่งบ่าย')], default='เต็มวัน', max_length=100)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('duration2', models.CharField(choices=[('เต็มวัน', 'เต็มวัน'), ('ครึ่งเช้า', 'ครึ่งเช้า'), ('ครึ่งบ่าย', 'ครึ่งบ่าย')], default='เต็มวัน', max_length=100)),
                ('upload', models.FileField(upload_to='file_uploads')),
                ('leave_contact', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('รออนุมัติ', 'รออนุมัติ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], default='รออนุมัติ', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('leave_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveappdata.settings_department_form')),
                ('leave_sort_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveappdata.settings_sort_form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaveappdata_leave_form',
            },
        ),
    ]
