# Generated by Django 3.2.4 on 2021-06-15 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_sort_name', models.CharField(choices=[('ลากิจส่วนตัว', 'ลากิจส่วนตัว'), ('ลาคลอดบุตร', 'ลาคลอดบุตร'), ('ลาป่วย', 'ลาป่วย'), ('ลาพักร้อน', 'ลาพักร้อน'), ('ลาเข้าตรวจรับเลือกทหารหรือเข้ารับการเตรียมพล', 'ลาเข้าตรวจรับเลือกทหารหรือเข้ารับการเตรียมพล'), ('ลาไปช่วยเหลือภรรยาที่คลอดบุตร', 'ลาไปช่วยเหลือภรรยาที่คลอดบุตร'), ('ลาไปศึกษา ฝึกอบรม ปฏิบัติการวิจัย หรือดูงาน', 'ลาไปศึกษา ฝึกอบรม ปฏิบัติการวิจัย หรือดูงาน')], default='ลากิจส่วนตัว', max_length=200)),
                ('leave_department', models.CharField(choices=[('บริหาร', 'บริหาร'), ('จัดซื้อจัดจ้าง', 'จัดซื้อจัดจ้าง'), ('บุคคล', 'บุคคล')], default='บริหาร', max_length=200)),
                ('leave_reason', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('duration1', models.CharField(choices=[('เต็มวัน', 'เต็มวัน'), ('ครึ่งเช้า', 'ครึ่งเช้า'), ('ครึ่งบ่าย', 'ครึ่งบ่าย')], default='เต็มวัน', max_length=100)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('duration2', models.CharField(choices=[('เต็มวัน', 'เต็มวัน'), ('ครึ่งเช้า', 'ครึ่งเช้า'), ('ครึ่งบ่าย', 'ครึ่งบ่าย')], default='เต็มวัน', max_length=100)),
                ('upload', models.FileField(upload_to='file_uploads')),
                ('leave_contact', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
