# Generated by Django 3.2.4 on 2021-07-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveappdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_sort_form',
            name='leave_conditions',
        ),
        migrations.RemoveField(
            model_name='settings_sort_form',
            name='leaveform',
        ),
        migrations.RemoveField(
            model_name='settings_sort_form',
            name='user',
        ),
        migrations.AlterField(
            model_name='leave_form',
            name='leave_sort_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveappdata.settings_sort_form'),
        ),
    ]
