# Generated by Django 3.2.4 on 2021-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveappdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_form',
            name='numdays',
        ),
        migrations.AlterField(
            model_name='settings_sort_form',
            name='leave_days',
            field=models.IntegerField(),
        ),
    ]
