# Generated by Django 3.2.4 on 2021-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveappdata', '0002_auto_20210712_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_sort_form',
            name='leave_days',
            field=models.CharField(max_length=2),
        ),
    ]
