# Generated by Django 3.2.4 on 2021-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveappdata', '0003_alter_settings_sort_form_leave_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_Department_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='settings_sort_form',
            name='leave_days',
            field=models.CharField(max_length=3),
        ),
    ]
