# Generated by Django 3.2.4 on 2021-07-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveappdata', '0004_auto_20210713_1412'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settings_department_form',
            table='leaveappdata_settings_department_form',
        ),
    ]
